# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: G's blog
email: guilherme.carvalho@gmail.com
description: talking about life, technology and other things
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github.io/guigacarvalho" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Guilherme Carvalho'
bio: >
  I'm curious. 🤓 Software developer by trade, usually working with Vue.JS and React. 
  When I'm not engineering, I like to surf, woodwork, hike, geek around and hangout with friends.
author_image: "/assets/images/author.jpg"
twitter_username: guigacarvalho
github_username:  guigacarvalho

# Google Analytics
analytics_id: "UA-77096743-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
